version: '3.1'

services:

  db:
    image: arm32v7/postgres:11.1
    restart: always
    environment:
      POSTGRES_PASSWORD: passwdb
      POSTGRES_USER: userdb 
    ports:
      - "5432:5432"
    volumes:
      - ./res/db:/docker-entrypoint-initdb.d
      - ./data_docker/postgresql:/var/lib/postgresql/data

  python:
    image: pythonflask
    build:
            context: docker_files
            dockerfile: Docker_flask
    ports:
        - "80:80"
    volumes:
            - ./src:/mypower
            - /etc/localtime:/etc/localtime
